# .streamlit/config.toml
[theme]
base="dark"
primaryColor="#8AE234"      # verde del logo
backgroundColor="#0E1117"   # fondo app
secondaryBackgroundColor="#141821"  # paneles / sidebar
textColor="#E6E6E6"
font="sans serif"
